CALL .\run_synthea.bat -p 182 "Alabama"
CALL .\run_synthea.bat -p 33 "Alaska"
CALL .\run_synthea.bat -p 251 "Arizona"
CALL .\run_synthea.bat -p 110 "Arkansas"
CALL .\run_synthea.bat -p 861 "California"
CALL .\run_synthea.bat -p 198 "Colorado"
CALL .\run_synthea.bat -p 96 "Connecticut"
CALL .\run_synthea.bat -p 35 "Delaware"
CALL .\run_synthea.bat -p 14 "District of Columbia"
CALL .\run_synthea.bat -p 767 "Florida"
CALL .\run_synthea.bat -p 337 "Georgia"
CALL .\run_synthea.bat -p 55 "Hawaii"
CALL .\run_synthea.bat -p 60 "Idaho"
CALL .\run_synthea.bat -p 320 "Illinois"
CALL .\run_synthea.bat -p 206 "Indiana"
CALL .\run_synthea.bat -p 104 "Iowa"
CALL .\run_synthea.bat -p 96 "Kansas"
CALL .\run_synthea.bat -p 145 "Kentucky"
CALL .\run_synthea.bat -p 140 "Louisiana"
CALL .\run_synthea.bat -p 58 "Maine"
CALL .\run_synthea.bat -p 197 "Maryland"
CALL .\run_synthea.bat -p 168 "Massachusetts"
CALL .\run_synthea.bat -p 302 "Michigan"
CALL .\run_synthea.bat -p 167 "Minnesota"
CALL .\run_synthea.bat -p 94 "Mississippi"
CALL .\run_synthea.bat -p 221 "Missouri"
CALL .\run_synthea.bat -p 45 "Montana"
CALL .\run_synthea.bat -p 65 "Nebraska"
CALL .\run_synthea.bat -p 108 "Nevada"
CALL .\run_synthea.bat -p 53 "New Hampshire"
CALL .\run_synthea.bat -p 187 "New Jersey"
CALL .\run_synthea.bat -p 79 "New Mexico"
CALL .\run_synthea.bat -p 403 "New York"
CALL .\run_synthea.bat -p 352 "North Carolina"
CALL .\run_synthea.bat -p 25 "North Dakota"
CALL .\run_synthea.bat -p 394 "Ohio"
CALL .\run_synthea.bat -p 149 "Oklahoma"
CALL .\run_synthea.bat -p 153 "Oregon"
CALL .\run_synthea.bat -p 420 "Pennsylvania"
CALL .\run_synthea.bat -p 33 "Rhode Island"
CALL .\run_synthea.bat -p 195 "South Carolina"
CALL .\run_synthea.bat -p 32 "South Dakota"
CALL .\run_synthea.bat -p 230 "Tennessee"
CALL .\run_synthea.bat -p 771 "Texas"
CALL .\run_synthea.bat -p 66 "Utah"
CALL .\run_synthea.bat -p 22 "Vermont"
CALL .\run_synthea.bat -p 353 "Virginia"
CALL .\run_synthea.bat -p 277 "Washington"
CALL .\run_synthea.bat -p 71 "West Virginia"
CALL .\run_synthea.bat -p 184 "Wisconsin"
CALL .\run_synthea.bat -p 23 "Wyoming"
